input {
  tcp {
    port => 5044
    codec => json_lines
  }
  udp {
    port => 5044
    codec => json_lines
  }
  http {
    port => 8080
    codec => json
  }
}

filter {
  if [type] == "backend" {
    mutate {
      add_tag => ["sovereign-backend"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "sovereign-logs-%{+YYYY.MM.dd}"
    # user => "elastic"
    # password => "changeme"
  }
  stdout { codec => rubydebug }
}
